
import React from 'react';
import { Spinner } from './Spinner';

interface ImageDisplayProps {
  imageUrl: string | null;
  isLoading: boolean;
  error: string | null;
}

const Placeholder: React.FC = () => (
    <div className="flex flex-col items-center justify-center h-full text-center text-slate-500">
        <svg xmlns="http://www.w3.org/2000/svg" className="h-16 w-16 mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
        </svg>
        <h3 className="text-xl font-semibold text-slate-300">Your masterpiece awaits</h3>
        <p className="mt-1">Enter a prompt and let the AI bring your vision to life.</p>
    </div>
);

const ErrorDisplay: React.FC<{ message: string }> = ({ message }) => (
    <div className="flex flex-col items-center justify-center h-full text-center text-red-400 p-4">
        <svg xmlns="http://www.w3.org/2000/svg" className="h-12 w-12 mb-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2">
            <path strokeLinecap="round" strokeLinejoin="round" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <h3 className="text-lg font-semibold">Oops! Something went wrong.</h3>
        <p className="text-sm">{message}</p>
    </div>
);

export const ImageDisplay: React.FC<ImageDisplayProps> = ({ imageUrl, isLoading, error }) => {
  return (
    <div className="w-full aspect-square bg-slate-800/50 rounded-2xl flex items-center justify-center p-4 border-2 border-dashed border-slate-700 relative overflow-hidden transition-all duration-300">
      {isLoading && (
        <div className="absolute inset-0 bg-slate-900/50 flex items-center justify-center z-10 backdrop-blur-sm">
          <Spinner />
        </div>
      )}
      {!isLoading && error && <ErrorDisplay message={error} />}
      {!isLoading && !error && !imageUrl && <Placeholder />}
      {!isLoading && !error && imageUrl && (
        <img
          src={imageUrl}
          alt="Generated by AI"
          className="max-w-full max-h-full object-contain rounded-lg shadow-2xl"
        />
      )}
    </div>
  );
};
